import type React from "react"
import type { Metadata } from "next"
// import { GeistSans } from "geist/font/sans"
// import { GeistMono } from "geist/font/mono"
// import { Analytics } from "@vercel/analytics/next"
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react"
import { WalletProvider as SolanaWalletProvider } from "@/contexts/WalletProvider"
import { WalletProvider } from "@/lib/wallet-context"
import { Toaster } from "@/components/ui/toaster"
import { Sidebar } from "@/components/sidebar"
// import { PageTransition } from "@/components/page-transition"
import "./globals.css"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "MultiVault - Blockchain Asset Tokenization Platform",
  description: "Transform real and digital assets into tradeable tokens with fractional ownership and global liquidity",
  generator: "v0.app",
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    apple: "/favicon.svg",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SolanaWalletProvider>
          <WalletProvider>
            <div className="flex h-screen">
              <Sidebar />
              <main className="flex-1 lg:ml-64 overflow-auto">
                <Suspense fallback={
                  <div className="min-h-screen flex items-center justify-center bg-background">
                    <div className="flex flex-col items-center gap-4">
                      <div className="animate-spin rounded-full border-2 border-primary border-t-transparent w-8 h-8" />
                      <p className="text-muted-foreground">Loading...</p>
                    </div>
                  </div>
                }>
                  {children}
                </Suspense>
              </main>
            </div>
            <Toaster />
          </WalletProvider>
        </SolanaWalletProvider>
      </body>
    </html>
  )
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
